[package]
name = "your_contract_name"
version = "0.1.0"
edition = "2018"

[dependencies]
near-sdk = "4.0.0-pre.4"
borsh = "0.9"
serde = { version = "1.0", features = ["derive"] }

[lib]
crate-type = ["cdylib"]

[profile.release]
# Reduces size of the compiled .wasm file
opt-level = "z"
lto = true
codegen-units = 1
