[package]
name = "rustlette_gambling_game"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
near-sdk = "4.0.0-pre.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
crate-type = ["cdylib"]